-- ===========================================================================
-- 0000_baseline - playZ / CHRTV production schema
--
-- GENERATED by scripts/gen-d1-baseline.mjs. Do not hand-edit; re-run the
-- generator after changing SCHEMA_STATEMENTS in worker/worker.js.
--
-- Why this file exists
-- --------------------
-- Production was provisioned by hand (wrangler d1 execute --file=schema.sql)
-- and then kept current by ensureSchema() running CREATE TABLE IF NOT EXISTS
-- plus try/catch ALTER TABLE ADD COLUMN on every cold isolate. That works, but
-- it leaves the database with no migration history: D1 own d1_migrations
-- table is empty, so the first "wrangler d1 migrations apply" would try to run
-- every statement again.
--
-- This baseline is written so that is safe:
--
--   * every table is created with IF NOT EXISTS  -> existing tables untouched
--   * every column that ensureSchema() ever added by ALTER is folded into the
--     CREATE TABLE, so a fresh database is born at the current shape
--   * every index is created with IF NOT EXISTS
--
-- There is no DROP, no DELETE, no data rewrite anywhere in this file. Applying
-- it to a populated production database changes nothing; applying it to an
-- empty one produces exactly the schema the Worker expects.
--
-- Tables: 78 / indexes: 24
-- ===========================================================================

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  avatar_url TEXT DEFAULT '',
  display_name TEXT DEFAULT '',
  role TEXT DEFAULT 'user',
  email_verified INTEGER DEFAULT 0,
  verify_code TEXT DEFAULT '',
  verify_expires INTEGER DEFAULT 0,
  reset_token TEXT DEFAULT '',
  reset_expires INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  banned INTEGER DEFAULT 0,
  totp_secret TEXT DEFAULT '',
  totp_enabled INTEGER DEFAULT 0,
  plan TEXT DEFAULT ''
);;

CREATE TABLE IF NOT EXISTS sessions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  token TEXT UNIQUE NOT NULL,
  expires_at INTEGER NOT NULL,
  user_agent TEXT DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  ip TEXT DEFAULT ''
);;

CREATE TABLE IF NOT EXISTS feedback (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER DEFAULT 0,
  channel_id TEXT DEFAULT '',
  message TEXT NOT NULL,
  client_info TEXT DEFAULT '',
  status TEXT DEFAULT 'new',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS shorts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT DEFAULT '',
  caption TEXT DEFAULT '',
  video_url TEXT NOT NULL,
  thumb_url TEXT DEFAULT '',
  duration INTEGER DEFAULT 0,
  author TEXT DEFAULT '',
  views INTEGER DEFAULT 0,
  likes INTEGER DEFAULT 0,
  status TEXT DEFAULT 'live',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  user_id INTEGER DEFAULT 0,
  creator_id INTEGER DEFAULT 0,
  hashtags TEXT DEFAULT ''
);;

CREATE TABLE IF NOT EXISTS qr_logins (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT UNIQUE NOT NULL,
  user_id INTEGER DEFAULT 0,
  status TEXT DEFAULT 'pending',
  device_info TEXT DEFAULT '',
  created_at INTEGER NOT NULL,
  expires_at INTEGER NOT NULL
);;

CREATE TABLE IF NOT EXISTS sports_videos (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  league TEXT DEFAULT '',
  thumb_url TEXT DEFAULT '',
  video_url TEXT NOT NULL,
  duration TEXT DEFAULT '',
  is_active INTEGER DEFAULT 1,
  sort_order INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS events (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  subtitle TEXT DEFAULT '',
  image_url TEXT DEFAULT '',
  link_type TEXT DEFAULT 'none',
  link_value TEXT DEFAULT '',
  starts_at TEXT DEFAULT '',
  ends_at TEXT DEFAULT '',
  is_active INTEGER DEFAULT 1,
  sort_order INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  blocked_regions TEXT DEFAULT ''
);;

CREATE TABLE IF NOT EXISTS plans (
  code TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  rank INTEGER DEFAULT 1,
  price INTEGER DEFAULT 0,
  price_text TEXT DEFAULT '',
  tagline TEXT DEFAULT '',
  allows TEXT DEFAULT '[]',
  color TEXT DEFAULT '#f36f21',
  is_active INTEGER DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS user_settings (
  user_id INTEGER PRIMARY KEY,
  theme TEXT DEFAULT 'dark',
  default_quality TEXT DEFAULT 'auto',
  buffer_goal INTEGER DEFAULT 10,
  language TEXT DEFAULT 'vi',
  parental_pin TEXT DEFAULT '',
  parental_enabled INTEGER DEFAULT 0,
  settings_json TEXT DEFAULT '{}',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS user_favorites (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  channel_id TEXT NOT NULL,
  sort_order INTEGER DEFAULT 0,
  group_name TEXT DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, channel_id)
);;

CREATE TABLE IF NOT EXISTS watch_history (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  channel_id TEXT NOT NULL,
  last_position INTEGER DEFAULT 0,
  watch_count INTEGER DEFAULT 1,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, channel_id)
);;

CREATE TABLE IF NOT EXISTS channels (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  channel_id TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  logo TEXT DEFAULT '',
  group_title TEXT DEFAULT '',
  stream_url TEXT NOT NULL,
  catchup_type TEXT DEFAULT 'append',
  catchup_days INTEGER DEFAULT 7,
  is_active INTEGER DEFAULT 1,
  user_agent TEXT DEFAULT '',
  referer TEXT DEFAULT '',
  manifest_type TEXT DEFAULT '',
  license_type TEXT DEFAULT '',
  clear_key_id TEXT DEFAULT '',
  clear_key TEXT DEFAULT '',
  stream_token TEXT DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  blocked_regions TEXT DEFAULT '',
  is_sponsored INTEGER DEFAULT 0,
  protect INTEGER DEFAULT 1
);;

CREATE TABLE IF NOT EXISTS channel_ratings (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  channel_id TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  rating INTEGER NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(channel_id, user_id)
);;

CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  body TEXT NOT NULL,
  type TEXT DEFAULT 'info',
  channel_id TEXT DEFAULT '',
  url TEXT DEFAULT '',
  is_read INTEGER DEFAULT 0,
  target TEXT DEFAULT 'all',
  created_by INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  expires_at INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS analytics (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  event TEXT NOT NULL,
  user_id INTEGER DEFAULT 0,
  channel_id TEXT DEFAULT '',
  data TEXT DEFAULT '{}',
  ip TEXT DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS program_reminders (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  channel_id TEXT NOT NULL,
  program_title TEXT NOT NULL,
  remind_at DATETIME NOT NULL,
  is_sent INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS epg_cache (
  key TEXT PRIMARY KEY,
  data TEXT NOT NULL,
  expires_at INTEGER NOT NULL
);;

CREATE TABLE IF NOT EXISTS epg_overrides (
  channel_id TEXT PRIMARY KEY,
  channel_name TEXT DEFAULT '',
  programmes TEXT NOT NULL,
  updated_at INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS m3u_sources (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  url TEXT NOT NULL,
  is_active INTEGER DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS broadcasts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  message TEXT NOT NULL,
  type TEXT DEFAULT 'info',
  is_active INTEGER DEFAULT 1,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  expires_at INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS user_profiles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  name TEXT NOT NULL,
  avatar_url TEXT DEFAULT '',
  is_child INTEGER DEFAULT 0,
  pin_hash TEXT DEFAULT '',
  active INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS login_attempts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  login TEXT NOT NULL,
  ip TEXT DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS audit_log (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER DEFAULT 0,
  action TEXT NOT NULL,
  detail TEXT DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS movie_watchlist (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  media_type TEXT DEFAULT 'movie',
  tmdb_id INTEGER NOT NULL,
  title TEXT DEFAULT '',
  poster_path TEXT DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(user_id, media_type, tmdb_id)
);;

CREATE TABLE IF NOT EXISTS push_subscriptions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER DEFAULT 0,
  endpoint TEXT UNIQUE NOT NULL,
  p256dh TEXT DEFAULT '',
  auth TEXT DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS push_config (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL
);;

CREATE TABLE IF NOT EXISTS tmdb_cache (
  key TEXT PRIMARY KEY,
  data TEXT NOT NULL,
  expires_at INTEGER NOT NULL
);;

CREATE TABLE IF NOT EXISTS rate_limits (
  key TEXT PRIMARY KEY,
  hits INTEGER DEFAULT 0,
  window_start INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS stream_credentials (
  channel_id TEXT PRIMARY KEY,
  upstream_token TEXT NOT NULL,
  updated_at INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS party_rooms (
  room TEXT PRIMARY KEY,
  channel_id TEXT DEFAULT '',
  channel_name TEXT DEFAULT '',
  updated_at INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS party_members (
  room TEXT NOT NULL,
  name TEXT NOT NULL,
  last_seen INTEGER DEFAULT 0,
  PRIMARY KEY(room, name)
);;

CREATE TABLE IF NOT EXISTS party_messages (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  room TEXT NOT NULL,
  from_name TEXT DEFAULT '',
  kind TEXT DEFAULT 'chat',
  text TEXT DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS watch_counters (
  channel_id TEXT PRIMARY KEY,
  views INTEGER DEFAULT 0,
  seconds INTEGER DEFAULT 0,
  updated_at INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS presence (
  sid TEXT PRIMARY KEY,
  user_id INTEGER DEFAULT 0,
  name TEXT DEFAULT '',
  kind TEXT DEFAULT '',
  ref_id TEXT DEFAULT '',
  ref_name TEXT DEFAULT '',
  updated_at INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS user_xp (
  user_id INTEGER PRIMARY KEY,
  xp INTEGER DEFAULT 0,
  watch_sec INTEGER DEFAULT 0,
  updated_at INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS public_profiles (
  user_id INTEGER PRIMARY KEY,
  handle TEXT UNIQUE,
  bio TEXT DEFAULT '',
  avatar_url TEXT DEFAULT '',
  is_public INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS comments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  target TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  name TEXT DEFAULT '',
  body TEXT NOT NULL,
  status TEXT DEFAULT 'visible',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  tstamp INTEGER DEFAULT -1,
  voice_url TEXT DEFAULT '',
  kind TEXT DEFAULT 'comment',
  pinned INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS community_likes (
  target TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(target, user_id)
);;

CREATE TABLE IF NOT EXISTS fan_groups (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  target TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  created_by INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS fan_members (
  group_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
  name TEXT DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(group_id, user_id)
);;

CREATE TABLE IF NOT EXISTS gift_codes (
  code TEXT PRIMARY KEY,
  plan TEXT DEFAULT 'signature',
  days INTEGER DEFAULT 30,
  max_uses INTEGER DEFAULT 1,
  used INTEGER DEFAULT 0,
  is_active INTEGER DEFAULT 1,
  note TEXT DEFAULT '',
  created_by INTEGER DEFAULT 0,
  to_username TEXT DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS gift_redemptions (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  code TEXT NOT NULL,
  user_id INTEGER NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS user_plans (
  user_id INTEGER PRIMARY KEY,
  plan TEXT DEFAULT 'standard',
  expires_at INTEGER DEFAULT 0,
  updated_at INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS payments (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  username TEXT DEFAULT '',
  plan TEXT NOT NULL,
  amount INTEGER DEFAULT 0,
  order_code TEXT UNIQUE NOT NULL,
  status TEXT DEFAULT 'pending',
  payload TEXT DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  paid_at DATETIME DEFAULT NULL
);;

CREATE TABLE IF NOT EXISTS payment_config (
  id INTEGER PRIMARY KEY CHECK (id = 1),
  bank_id TEXT DEFAULT '',
  account_no TEXT DEFAULT '',
  account_name TEXT DEFAULT '',
  template TEXT DEFAULT 'compact2',
  sepay_token TEXT DEFAULT '',
  note TEXT DEFAULT ''
);;

CREATE TABLE IF NOT EXISTS ads (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  slot TEXT DEFAULT 'banner',
  title TEXT DEFAULT '',
  image_url TEXT DEFAULT '',
  link_url TEXT DEFAULT '',
  video_url TEXT DEFAULT '',
  starts_at TEXT DEFAULT '',
  ends_at TEXT DEFAULT '',
  is_active INTEGER DEFAULT 1,
  sort_order INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  blocked_regions TEXT DEFAULT ''
);;

CREATE TABLE IF NOT EXISTS movie_sources (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  kind TEXT DEFAULT 'embed',
  url_template TEXT NOT NULL,
  license_note TEXT DEFAULT '',
  is_active INTEGER DEFAULT 1,
  sort_order INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  blocked_regions TEXT DEFAULT '',
  label TEXT DEFAULT ''
);;

CREATE TABLE IF NOT EXISTS scheduled_posts (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  kind TEXT NOT NULL,
  title TEXT DEFAULT '',
  body TEXT DEFAULT '',
  link_type TEXT DEFAULT 'none',
  link_value TEXT DEFAULT '',
  image_url TEXT DEFAULT '',
  publish_at TEXT NOT NULL,
  is_done INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  end_at TEXT DEFAULT '',
  is_active INTEGER DEFAULT 1
);;

CREATE TABLE IF NOT EXISTS predictions (
  user_id INTEGER NOT NULL,
  event_key TEXT NOT NULL,
  league TEXT DEFAULT '',
  home TEXT DEFAULT '',
  away TEXT DEFAULT '',
  ph INTEGER DEFAULT 0,
  pa INTEGER DEFAULT 0,
  points INTEGER DEFAULT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY(user_id, event_key)
);;

CREATE TABLE IF NOT EXISTS short_creator_profiles (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_id INTEGER NOT NULL,
  handle TEXT UNIQUE NOT NULL,
  display_name TEXT DEFAULT '',
  avatar_url TEXT DEFAULT '',
  bio TEXT DEFAULT '',
  verified INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS short_follows (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  follower_user_id INTEGER NOT NULL,
  creator_id INTEGER NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  UNIQUE(follower_user_id, creator_id)
);;

CREATE TABLE IF NOT EXISTS channel_reports (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  channel_id TEXT NOT NULL,
  channel_name TEXT DEFAULT '',
  user_id INTEGER DEFAULT 0,
  code TEXT DEFAULT 'other',
  note TEXT DEFAULT '',
  ua TEXT DEFAULT '',
  status TEXT DEFAULT 'open',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS player_errors (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  channel_id TEXT DEFAULT '',
  channel_name TEXT DEFAULT '',
  engine TEXT DEFAULT '',
  code TEXT DEFAULT '',
  detail TEXT DEFAULT '',
  fatal INTEGER DEFAULT 0,
  platform TEXT DEFAULT '',
  user_id INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS channel_health (
  channel_id TEXT PRIMARY KEY,
  status TEXT DEFAULT 'unknown',
  http_code INTEGER DEFAULT 0,
  latency_ms INTEGER DEFAULT 0,
  fail_count INTEGER DEFAULT 0,
  ok_at INTEGER DEFAULT 0,
  checked_at INTEGER DEFAULT 0,
  note TEXT DEFAULT '',
  maintenance_until INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS watch_pulse (
  channel_id TEXT NOT NULL,
  bucket INTEGER NOT NULL,
  seconds INTEGER DEFAULT 0,
  views INTEGER DEFAULT 0,
  PRIMARY KEY(channel_id, bucket)
);;

CREATE TABLE IF NOT EXISTS jobs (
  name TEXT PRIMARY KEY,
  last_run INTEGER DEFAULT 0,
  running_until INTEGER DEFAULT 0,
  cursor TEXT DEFAULT '',
  last_result TEXT DEFAULT ''
);;

CREATE TABLE IF NOT EXISTS ad_views (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user_key TEXT NOT NULL,
  ad_id INTEGER DEFAULT 0,
  kind TEXT DEFAULT 'channel',
  ref_id TEXT DEFAULT '',
  plan TEXT DEFAULT '',
  completed INTEGER DEFAULT 0,
  created_at INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS preview_usage (
  user_key TEXT PRIMARY KEY,
  window_start INTEGER DEFAULT 0,
  seconds INTEGER DEFAULT 0,
  updated_at INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS movie_share_codes (
  code TEXT PRIMARY KEY,
  kind TEXT DEFAULT 'movie',
  media_type TEXT DEFAULT 'movie',
  tmdb_id INTEGER DEFAULT 0,
  season INTEGER DEFAULT 0,
  episode INTEGER DEFAULT 0,
  payload TEXT DEFAULT '',
  created_by INTEGER DEFAULT 0,
  created_by_name TEXT DEFAULT '',
  used INTEGER DEFAULT 0,
  expires_at INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS movie_progress (
  user_id INTEGER NOT NULL,
  media_type TEXT DEFAULT 'movie',
  tmdb_id INTEGER NOT NULL,
  season INTEGER DEFAULT 0,
  episode INTEGER DEFAULT 0,
  position_sec REAL DEFAULT 0,
  duration_sec REAL DEFAULT 0,
  percent REAL DEFAULT 0,
  title TEXT DEFAULT '',
  poster_path TEXT DEFAULT '',
  updated_at INTEGER DEFAULT 0,
  PRIMARY KEY (user_id, media_type, tmdb_id, season, episode)
);;

CREATE TABLE IF NOT EXISTS resume_codes (
  code TEXT PRIMARY KEY,
  user_id INTEGER NOT NULL,
  payload TEXT DEFAULT '',
  expires_at INTEGER DEFAULT 0,
  used INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS series_follows (
  user_id INTEGER NOT NULL,
  tmdb_id INTEGER NOT NULL,
  season INTEGER DEFAULT 0,
  episode INTEGER DEFAULT 0,
  updated_at INTEGER DEFAULT 0,
  PRIMARY KEY (user_id, tmdb_id)
);;

CREATE TABLE IF NOT EXISTS creator_stars (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  creator_id INTEGER NOT NULL,
  user_id INTEGER DEFAULT 0,
  stars INTEGER DEFAULT 1,
  created_at INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS challenges (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  title TEXT NOT NULL,
  hashtag TEXT DEFAULT '',
  description TEXT DEFAULT '',
  starts_at TEXT DEFAULT '',
  ends_at TEXT DEFAULT '',
  is_active INTEGER DEFAULT 1,
  created_by INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS watch_cc (
  channel_id TEXT NOT NULL,
  country TEXT NOT NULL,
  bucket INTEGER NOT NULL,
  seconds INTEGER DEFAULT 0,
  views INTEGER DEFAULT 0,
  PRIMARY KEY (channel_id, country, bucket)
);;

CREATE TABLE IF NOT EXISTS user_watch (
  user_id INTEGER NOT NULL,
  kind TEXT NOT NULL,
  ref_id TEXT NOT NULL,
  ref_name TEXT DEFAULT '',
  sec INTEGER DEFAULT 0,
  updated_at INTEGER DEFAULT 0,
  PRIMARY KEY (user_id, kind, ref_id)
);;

CREATE TABLE IF NOT EXISTS admin_alert_rules (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  metric TEXT DEFAULT '',
  op TEXT DEFAULT 'gt',
  threshold REAL DEFAULT 0,
  enabled INTEGER DEFAULT 1,
  cooldown_s INTEGER DEFAULT 3600,
  last_fired_at INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS admin_alert_feed (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  rule_id INTEGER DEFAULT 0,
  level TEXT DEFAULT 'warn',
  message TEXT NOT NULL,
  data TEXT DEFAULT '',
  ack INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS trending_searches (
  query TEXT PRIMARY KEY,
  cnt INTEGER DEFAULT 1,
  last_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS party_polls (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  room TEXT NOT NULL,
  question TEXT NOT NULL,
  options TEXT DEFAULT '[]',
  votes TEXT DEFAULT '[]',
  voters TEXT DEFAULT '[]',
  created_by INTEGER DEFAULT 0,
  ends_at INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS movie_wishlists (
  user_id INTEGER NOT NULL,
  tmdb_id INTEGER NOT NULL,
  media_type TEXT DEFAULT 'movie',
  notified_at INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, tmdb_id)
);;

CREATE TABLE IF NOT EXISTS actor_follows (
  user_id INTEGER NOT NULL,
  person_id INTEGER NOT NULL,
  name TEXT DEFAULT '',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, person_id)
);;

CREATE TABLE IF NOT EXISTS affiliates (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  kind TEXT DEFAULT 'cinema',
  url_template TEXT DEFAULT '',
  label TEXT DEFAULT '',
  enabled INTEGER DEFAULT 1,
  sort_order INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE TABLE IF NOT EXISTS user_quiz (
  user_id INTEGER PRIMARY KEY,
  answers_json TEXT DEFAULT '{}',
  done INTEGER DEFAULT 0,
  updated_at INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS team_follows (
  user_id INTEGER NOT NULL,
  team_name TEXT NOT NULL,
  updated_at INTEGER DEFAULT 0,
  PRIMARY KEY (user_id, team_name)
);;

CREATE TABLE IF NOT EXISTS site_config (
  key TEXT PRIMARY KEY,
  value TEXT NOT NULL,
  updated_at INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS channel_watermark (
  channel_id TEXT PRIMARY KEY,
  wm TEXT NOT NULL,
  updated_at INTEGER DEFAULT 0
);;

CREATE TABLE IF NOT EXISTS site_themes (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  key TEXT UNIQUE NOT NULL,
  name TEXT NOT NULL,
  emoji TEXT DEFAULT '',
  description TEXT DEFAULT '',
  primary_color TEXT DEFAULT '#f36f21',
  secondary_color TEXT DEFAULT '#1a1c24',
  accent_color TEXT DEFAULT '#ffb37a',
  background_url TEXT DEFAULT '',
  banner_url TEXT DEFAULT '',
  logo_url TEXT DEFAULT '',
  confetti TEXT DEFAULT 'none',
  css TEXT DEFAULT '',
  is_active INTEGER DEFAULT 0,
  starts_at TEXT DEFAULT '',
  ends_at TEXT DEFAULT '',
  sort_order INTEGER DEFAULT 0,
  created_by INTEGER DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);;

CREATE INDEX IF NOT EXISTS idx_login_attempts ON login_attempts(login, created_at);
CREATE INDEX IF NOT EXISTS idx_party_messages ON party_messages(room, id);
CREATE INDEX IF NOT EXISTS idx_watch_history_user ON watch_history(user_id);
CREATE INDEX IF NOT EXISTS idx_favorites_user ON user_favorites(user_id);
CREATE INDEX IF NOT EXISTS idx_notifications_target ON notifications(target);
CREATE INDEX IF NOT EXISTS idx_analytics_event ON analytics(event, created_at);
CREATE INDEX IF NOT EXISTS idx_program_reminders_user ON program_reminders(user_id);
CREATE INDEX IF NOT EXISTS idx_sessions_token ON sessions(token);
CREATE INDEX IF NOT EXISTS idx_presence_upd ON presence(updated_at);
CREATE INDEX IF NOT EXISTS idx_comments_target ON comments(target, status, id);
CREATE INDEX IF NOT EXISTS idx_community_likes_target ON community_likes(target);
CREATE INDEX IF NOT EXISTS idx_predictions_key ON predictions(event_key);
CREATE INDEX IF NOT EXISTS idx_short_follows_creator ON short_follows(creator_id);
CREATE INDEX IF NOT EXISTS idx_short_follows_follower ON short_follows(follower_user_id);
CREATE INDEX IF NOT EXISTS idx_channel_reports ON channel_reports(channel_id, status);
CREATE INDEX IF NOT EXISTS idx_player_errors ON player_errors(channel_id, created_at);
CREATE INDEX IF NOT EXISTS idx_channel_health_checked ON channel_health(checked_at);
CREATE INDEX IF NOT EXISTS idx_watch_pulse_bucket ON watch_pulse(bucket);
CREATE INDEX IF NOT EXISTS idx_ad_views_key ON ad_views(user_key, created_at);
CREATE INDEX IF NOT EXISTS idx_movie_share_codes_exp ON movie_share_codes(expires_at);
CREATE INDEX IF NOT EXISTS idx_creator_stars_c ON creator_stars(creator_id, created_at);
CREATE INDEX IF NOT EXISTS idx_admin_alert_feed ON admin_alert_feed(ack, id);
CREATE INDEX IF NOT EXISTS idx_gift_codes_creator ON gift_codes(created_by);
CREATE INDEX IF NOT EXISTS idx_shorts_creator ON shorts(creator_id);
